# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='token_field',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
